### ISSUE TITLE
CORS Policies Issue

### ISSUE THREAD

**Issue by Nickolausen** [berrysauce/pinned#2]
Hello,
I've been using your API in my personal website for around 2 months now and it always worked out very well. The website is a simple web application with only front-end developed in ReactJS. In the last period of time I noticed it stopped working due to CORS issues. The error I get in console is the following:
``` 
nicholasmagi.it/:1 
Access to fetch at 'https://pinned.berrysauce.me/get/Nickolausen' from origin 'https://nicholasmagi.it' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: 
Redirect is not allowed for a preflight request.
```
I'm using a simple fetch() call in my component —
```jsx
useEffect(() => {
        let fetchedRepos: GHRepoDetails[] = []

        // TODO: Fix CORS issue
        fetch("https://pinned.berrysauce.me/get/Nickolausen", 
            {
                method: "GET",
                mode: "cors", 
                headers: { 
                    "Access-Control-Allow-Origin": "*",
                    "Content-Type": "application/json" 
                }
            })
            .then((res) => res.json())
            .then((data) => {
                data.forEach((el: any) => {
                    fetchedRepos.push(
                        { 
                            author: `${el.author}`,
                            name: `${el.name}`,
                            description: `${el.description}`,
                            language: `${el.language}`,
                            stars: Number(el.stars)
                        })    
                    })
                    
                    setRepos(fetchedRepos)
                })
            .catch((e) => console.log(e))
    }, [])
```

Does it has anything to do with some recent commits?

**Comment by berrysauce** [comment]
Hi! Great to hear from someone using it! 😁 Can you try changing the domain from `pinned.berrysauce.me` to `pinned.berrysauce.dev`. I switched the domain but there's a redirect in place, which might not be compatible with the CORS config as the error says "Redirect is not allowed for a preflight request". Let me know if it works!

**Comment by Nickolausen** [comment]
Thank you man! I've been striving for days with this issue — now it works! Your API is the most straightforward one I've found. Good job 🙌🏼
